### ISSUE TITLE
Replace free heroku server

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker-server#5]

**Comment by hyjk2000** [comment]
There is a caveat to this approach though. If we switch to bare metal machine, we'll need a domain and [Let's Encrypt](https://letsencrypt.org) to keep HTTPS.

**Comment by just4fun** [comment]
The code has been deployed on my linode server and HTTPS has been enabled via [Let's Encrypt](https://letsencrypt.org) with new domain I just bought.

Here are some articles I referred to.

- https://code.lengstorf.com/deploy-nodejs-ssl-digitalocean/
- https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates

Now I'm working on travis so we will have CI soon.

**Comment by just4fun** [comment]
Changes have been merged into master.

**Comment by just4fun** [comment]
- https://oncletom.io/2016/travis-ssh-deploy/
- https://kjaer.io/travis/
- https://www.ssh.com/ssh/copy-id
- https://uedsky.com/2016-06/travis-deploy/

Some useful articles for me about Travis CI.
